print("     Selamat Datang di Konversi Python       ")
print(" Pilih Sistem Bilangan Yang Akan Dikonversi")
print("     1. Desimal   2. Oktal    3. Hexa    4. Biner")
pilihan = int(input())
if pilihan == 1: 
    print ("Masukkan angka desimal:")
    Nilai = int(input())
    Oktal = oct(int(Nilai))
    Hexa = hex(int(Nilai))
    Bin = bin(int(Nilai))
    print("Nilai oktal: ",str(Oktal[2:]))
    print("Nilai hexadesimal yaitu: ",str(Hexa[2:]))
    print("Nilai Biner: ",str(Bin[2:]))
elif pilihan == 2:
    print ("Masukkan angka oktal:")
    Nilai = int(input(),8)
    Hexa = hex(int(Nilai))
    Bin = bin(int(Nilai))
    print("Nilai desimal: ",str(Nilai))
    print("Nilai hexadesimal: ",str(Hexa[2:]))
    print("Nilai Biner: ",str(Bin[2:]))
elif pilihan == 3:
    print ("Masukkan angka hexa:")
    Nilai = int(input(),16)
    Oktal = oct(int(Nilai))
    Bin = bin(int(Nilai))
    print("Nilai desimal: ",str(Nilai))
    print("Nilai oktal: ",str(Oktal[2:]))
    print("Nilai Biner: ",str(Bin[2:]))
elif pilihan == 4:
    print("Masukkan angka biner:")
    Nilai = int(input(),2)
    Oktal = oct(int(Nilai))
    Hexa = hex(int(Nilai))
    print("Nilai desimal: ",str(Nilai))
    print("Nilai Oktal: ",str(Oktal[2:]))
    print("Nilai Hexanya: ",str(Hexa[2:]))